services:
  - type: web
    name: video-call-webrtc
    env: node
    plan: free
    buildCommand: |
      echo "Building client..."
      cd client
      npm ci
      npm run build
      echo "Installing server dependencies..."
      cd ../server
      npm ci
      echo "Copying client build to server public..."
      mkdir -p public
      cp -r ../client/dist/* public/
      echo "Build completed successfully"
    startCommand: cd server && node src/server.js
    envVars:
      - key: NODE_ENV
        value: production